repositories:
  - name: common
    url: git+https://github.com/latin-ua/common_chart/@chart

releases:
  - name: latin-ua-back-end
    chart: common/common-chart
    namespace: default
    values:
      - values.yml.gotmpl
