name: Master pipeline
on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    container: docker.io/python:3.10-alpine
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python3 ./test.py

  build-and-push-image:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
