name: test
on:
  pull_request:
    types: [ reopened ]
  push:
    branches-ignore:
      - 'master'

jobs:

  tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    container: docker.io/python:3.10-alpine
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python3 ./src/test.py

  code_style:
    name: Run Code Style Tests
    runs-on: ubuntu-latest
    container: docker.io/python:3.10-alpine
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-test.txt
      - name: Run Flake8
        run: flake8 ./src/
