name: unittest
on:
  pull_request:
    types: [opened, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    container: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    needs: build-and-push-image
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run unittest
        run: python3 /test.py


  #if_merged:
    #if: github.event.pull_request.merged == true
    #runs-on: ubuntu-latest
    #steps:
      #- run: |
          #echo The PR was merged
